spring:
  application:
    name: testSecurity
  mvc:
    view:
#      prefix: html
      suffix: html
eureka: 
  instance: 
    hostname : localhost
  client : 
    serviceUrl: 
      defaultZone :  http://root:235610@localhost:8761/eureka

server: 
  port: 7777
