server: 
  port : 2202
eureka: 
  instance: 
    hostname : localhost
  client : 
    serviceUrl: 
      defaultZone :  http://root:235610@127.0.0.1:8761/eureka/
hystrix:
  metrics:
    polling-interval-ms: 5000

spring:
  application: 
    name: spring-rabbitmq
  rabbitmq:
    host: 132.232.0.46
    port: 5672            #统一为5672端口
    username: handsome    #为rabbitMQ-web端里添加的用户名
    password: handsome    #密码
    virtual-host: /       #root添加的虚拟地址，就像server-path一样
        
        
        