#---
#server:
#  port: 8761
#spring:
#  profiles: peer1
#  application:
#    name: eureka-ha
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    serviceUrl:
#      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
#
#---
#server:
#  port: 8762
#spring:
#  profiles: peer2
#  application:
#    name: eureka-ha
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
#
#---
#server:
#  port: 8763
#spring:
#  profiles: peer3
#  application:
#    name: eureka-ha
#eureka:
#  instance:
#    hostname: peer3
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

spring:
  profiles: eureka-server1
  application: 
    name: eureka-server
  security:
    user: 
      name: root  
      password: 235610
server: 
  port: 8761 #启动端口
  
logging:
  path: /root/eureka_server/logs
  
eureka: 
  instance:
    hostname: eureka-server1
  client:
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    registerWithEureka: false
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://root:235610@127.0.0.1:8761/eureka/ 
      ##defaultZone: http://root:235610@127.0.0.1:8762/eureka/ 
---
spring:
  profiles: eureka-server2
  application:
    name: eureka-server
  security:
    user: 
      name: root  
      password: 235610
server: 
  port: 8762 #启动端口
  
logging:
  path: /root/eureka_server/logs
  
eureka: 
  instance:
    hostname: eureka-server2   
  client:
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    registerWithEureka: false
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://root:235610@127.0.0.1:8761/eureka/ 
      
