server: 
  port : 81
  servlet:
    context-path: /taotask
eureka: 
  instance: 
    hostname : localhost
  client : 
    serviceUrl: 
      defaultZone :  http://root:235610@127.0.0.1:8761/eureka/

spring:
  profiles: taotask1
  application: 
    name: taotask
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/taoshelf?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 235610
    ##连接池
    hikari: 
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  thymeleaf: 
    mode:  HTML5
    encoding:  UTF-8
    cache:  false
  session:
    store-type: redis
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  redis: 
    #    host: 172.20.10.9
    #    host: 192.168.1.139
    host: 127.0.0.1
    port: 6379
    password: 
    jedis: 
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 10 
logging: 
  path: /root/taoTask/logs
mybatis-plus: 
  mapper-locations: classpath*:com/youmeng/taotask/xml/**Mapper.xml
  #configuration:
    #控制台输出sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  server:
    port: 8181
    servlet:
      context-path: /actuator
  endpoint: 
    health:
      show-details: ALWAYS  #显示详细信息
    env:
      enabled: true
  endpoints:
    web: 
      exposure:
        include: "*"   #暴露所有节点
---
server: 
  port : 91
  servlet:
    context-path: /taotask
eureka:   
  instance: 
    hostname : localhost
  client : 
    serviceUrl: 
      defaultZone :  http://root:235610@127.0.0.1:8761/eureka/

spring:
  profiles: taotask2
  application: 
    name: taotask
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/taoshelf?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    ##连接池
    hikari: 
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  thymeleaf: 
    mode:  HTML5
    encoding:  UTF-8
    cache:  false
  session:
    store-type: redis
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  redis: 
    #    host: 172.20.10.9
    #    host: 192.168.1.139
    host: 127.0.0.1
    port: 6379
    password: 
    jedis: 
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 10
#logging: 
#  path: /root/taoTask/logs
mybatis-plus: 
  mapper-locations: classpath*:com/youmeng/taotask/xml/**Mapper.xml
  #configuration:
    #控制台输出sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  server:
    port: 9191
    servlet:
      context-path: /actuator
  endpoint: 
    health:
      show-details: ALWAYS  #显示详细信息
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有节点