
spring:
  application:
    name: service-auth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: root
    password: root

  
server:
  port: 5000

security:
  oauth2:
    resource:
      filter-order: 3
      
mybatis-plus: 
  mapper-locations: classpath:mapper/*Mapper.xml
#  basic:
#    enabled: false


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
